// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/pricing.ts
var CONDITIONS = [
  { id: "light", label: "Light / Well-maintained", multiplier: 1 },
  { id: "moderate", label: "Moderate dirt", multiplier: 1.2 },
  { id: "heavy", label: "Heavy dirt / Neglected", multiplier: 1.4 },
  { id: "post-construction", label: "Post-construction debris", multiplier: 1.6 }
];
var ADD_ONS = [
  { id: "seat-removal", label: "Seat Removal", amount: 150 },
  { id: "engine-bay", label: "Engine Bay Clean", amount: 200 },
  { id: "headlight-restore", label: "Headlight Restoration", amount: 250 },
  { id: "windows-interior", label: "Interior Windows (up to 10)", amount: 350 },
  { id: "windows-exterior", label: "Exterior Windows (up to 10)", amount: 500 },
  { id: "sofa-clean", label: "Sofa / Upholstery Clean (3-seater)", amount: 400 },
  { id: "carpet-clean", label: "Carpet Deep Clean (per room)", amount: 300 },
  { id: "fridge-oven", label: "Inside Fridge & Oven", amount: 200 }
];
var SERVICES = [
  {
    id: "general-cleaning",
    label: "General Cleaning (Interior)",
    allowsDropOff: false,
    addOnIds: ["windows-interior", "windows-exterior", "sofa-clean", "carpet-clean", "fridge-oven"],
    sizes: [
      { id: "1-bed", label: "1 Bedroom", base: 550 },
      { id: "2-bed", label: "2 Bedroom", base: 700 },
      { id: "3-bed", label: "3 Bedroom", base: 900 },
      { id: "4-bed", label: "4 Bedroom", base: 1100 }
    ]
  },
  {
    id: "deep-cleaning",
    label: "Deep Cleaning",
    allowsDropOff: false,
    addOnIds: ["windows-interior", "windows-exterior", "sofa-clean", "carpet-clean", "fridge-oven"],
    sizes: [
      { id: "1-bed", label: "1 Bedroom", base: 850 },
      { id: "2-bed", label: "2 Bedroom", base: 1200 },
      { id: "3-bed", label: "3 Bedroom", base: 1800 },
      { id: "4-bed", label: "4 Bedroom", base: 2500 }
    ]
  },
  {
    id: "post-construction",
    label: "Post-Construction Cleaning",
    allowsDropOff: false,
    addOnIds: ["windows-interior", "windows-exterior", "carpet-clean"],
    sizes: [
      { id: "1-bed", label: "1 Bedroom", base: 1500 },
      { id: "2-bed", label: "2 Bedroom", base: 2e3 },
      { id: "3-bed", label: "3 Bedroom", base: 2800 },
      { id: "4-bed", label: "4 Bedroom", base: 3500 }
    ]
  },
  {
    id: "car-interior",
    label: "Car Detailing \u2013 Interior Deep Clean",
    allowsDropOff: true,
    addOnIds: ["seat-removal", "engine-bay"],
    sizes: [
      { id: "small", label: "Small Car / Sedan", base: 450 },
      { id: "suv", label: "SUV / 4x4", base: 550 }
    ]
  },
  {
    id: "car-full",
    label: "Car Detailing \u2013 Full (Interior + Exterior)",
    allowsDropOff: true,
    addOnIds: ["seat-removal", "engine-bay", "headlight-restore"],
    sizes: [
      { id: "small", label: "Small Car / Sedan", base: 650 },
      { id: "suv", label: "SUV / 4x4", base: 850 }
    ]
  },
  {
    id: "fumigation",
    label: "Fumigation & Pest Control",
    allowsDropOff: false,
    addOnIds: [],
    sizes: [
      { id: "residential", label: "Residential", base: 400 },
      { id: "commercial", label: "Commercial", base: 800 },
      { id: "termite", label: "Termite Treatment", base: 1200 }
    ]
  },
  {
    id: "office-cleaning",
    label: "Office Cleaning",
    allowsDropOff: false,
    addOnIds: ["windows-interior", "windows-exterior", "carpet-clean"],
    sizes: [
      { id: "daily", label: "Daily (per day)", base: 200 },
      { id: "weekly", label: "Weekly", base: 800 },
      { id: "monthly", label: "Monthly", base: 2800 }
    ]
  },
  {
    id: "trained-maids",
    label: "Trained Maids & Housekeeping",
    allowsDropOff: false,
    addOnIds: [],
    sizes: [
      { id: "daily", label: "Daily (per day)", base: 150 },
      { id: "live-in", label: "Live-in (monthly)", base: 2500 }
    ]
  },
  {
    id: "pools",
    label: "Swimming Pool Servicing & Cleaning",
    allowsDropOff: false,
    addOnIds: [],
    sizes: [
      { id: "standard", label: "Standard Pool Service", base: 800 },
      { id: "large", label: "Large Pool / Green Recovery", base: 1500 }
    ]
  },
  {
    id: "facility-management",
    label: "Facility Management",
    allowsDropOff: false,
    addOnIds: ["windows-interior", "windows-exterior", "carpet-clean"],
    sizes: [
      { id: "monthly", label: "Monthly contract", base: 2500 }
    ]
  },
  {
    id: "other",
    label: "Other / Multiple Services (custom quote)",
    allowsDropOff: false,
    addOnIds: ["windows-interior", "windows-exterior", "sofa-clean", "carpet-clean", "fridge-oven"],
    sizes: [
      { id: "custom", label: "Custom scope \u2014 describe below", base: 550 }
    ]
  }
];
var TRANSPORT_ZONES = [
  { id: "zone-1", label: "0\u20135 km from Kabulonga", amount: 120, areas: ["Kabulonga", "Sunningdale", "Woodlands", "Ibex Hill (near)"] },
  { id: "zone-2", label: "5\u201310 km from Kabulonga", amount: 180, areas: ["Rhodes Park", "Roma", "Longacres", "Olympia"] },
  { id: "zone-3", label: "10\u201320 km from Kabulonga", amount: 250, areas: ["Ibex Hill", "Meanwood", "Avondale", "Chalala", "Chelstone"] },
  { id: "zone-4", label: "20 km+ / outside Lusaka", amount: 350, areas: ["Chongwe", "Airport Road", "Ngwerere", "Makeni Far"] }
];
var round = (n) => Math.round(n);
function getService(serviceId) {
  return SERVICES.find((s) => s.id === serviceId);
}
function getTransportAmount(input) {
  if (input.serviceMode === "dropoff") return 0;
  const zone = TRANSPORT_ZONES.find((z3) => z3.id === input.transportZoneId);
  return zone ? zone.amount : 0;
}
function calculatePrice(input) {
  const service = getService(input.serviceId);
  if (!service) throw new Error(`Unknown service: ${input.serviceId}`);
  const size = service.sizes.find((s) => s.id === input.sizeId);
  if (!size) throw new Error(`Unknown size: ${input.sizeId} for ${input.serviceId}`);
  const condition = CONDITIONS.find((c) => c.id === input.conditionId);
  const multiplier = condition ? condition.multiplier : 1;
  const basePrice = size.base;
  const adjustedBase = round(basePrice * multiplier);
  const conditionAdjustment = adjustedBase - basePrice;
  const selectedAddOns = (input.addOnIds || []).map((id) => ADD_ONS.find((a) => a.id === id)).filter((a) => Boolean(a));
  const addOnsTotal = selectedAddOns.reduce((sum, a) => sum + a.amount, 0);
  const transport = getTransportAmount(input);
  const total = adjustedBase + addOnsTotal + transport;
  const missing = (condition ? 0 : 1) + (input.serviceMode === "mobile" && !input.transportZoneId ? 1 : 0);
  const confidence = missing === 0 ? "high" : missing === 1 ? "medium" : "low";
  const uncertainty = confidence === "high" ? 0.1 : confidence === "medium" ? 0.2 : 0.3;
  const breakdown = [
    { item: `Base Service \u2014 ${service.label} (${size.label})`, amount: basePrice }
  ];
  if (conditionAdjustment !== 0 && condition) {
    breakdown.push({
      item: `Condition Adjustment \u2014 ${condition.label} (${condition.multiplier}\xD7 on base)`,
      amount: conditionAdjustment
    });
  }
  selectedAddOns.forEach((a) => breakdown.push({ item: a.label, amount: a.amount }));
  breakdown.push({
    item: input.serviceMode === "dropoff" ? "Transport \u2014 Customer drop-off" : "Transport \u2014 Yango return trip",
    amount: transport
  });
  return {
    basePrice,
    conditionMultiplier: multiplier,
    conditionAdjustment,
    adjustedBase,
    addOnsTotal,
    transport,
    total,
    range: { min: total, max: round(total * (1 + uncertainty)) },
    breakdown,
    confidence,
    serviceLabel: `${service.label} \u2014 ${size.label}`
  };
}

// src/lib/mcp/tools/list-services.ts
var list_services_default = defineTool({
  name: "list_services",
  title: "List services and options",
  description: "List WeWash services, sizes, add-ons, conditions and transport zones with starting prices in ZMW.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const data = {
      services: SERVICES.map((s) => ({
        id: s.id,
        label: s.label,
        allowsDropOff: s.allowsDropOff,
        addOnIds: [...s.addOnIds],
        sizes: s.sizes.map((z3) => ({ id: z3.id, label: z3.label, startingFrom: z3.base }))
      })),
      addOns: ADD_ONS.map((a) => ({ id: a.id, label: a.label, amount: a.amount })),
      conditions: CONDITIONS.map((c) => ({ id: c.id, label: c.label, multiplier: c.multiplier })),
      transportZones: TRANSPORT_ZONES.map((t) => ({ id: t.id, amount: t.amount }))
    };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/estimate-price.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25";
var estimate_price_default = defineTool2({
  name: "estimate_price",
  title: "Estimate price",
  description: "Calculate a 'starting from' WeWash price estimate in ZMW. The team must confirm the final price.",
  inputSchema: {
    serviceId: z.string().describe("Service id from list_services."),
    sizeId: z.string().describe("Size id for that service."),
    conditionId: z.string().optional().describe("Condition id, if known."),
    addOnIds: z.array(z.string()).optional().describe("Add-on ids."),
    serviceMode: z.enum(["mobile", "dropoff"]).default("mobile"),
    transportZoneId: z.string().optional().describe("Transport zone id for mobile service.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    try {
      const r = calculatePrice(input);
      const data = {
        service: r.serviceLabel,
        startingFrom: r.total,
        rangeMax: r.range.max,
        currency: "ZMW",
        confidence: r.confidence,
        breakdown: r.breakdown.map((b) => ({ item: b.item, amount: b.amount })),
        note: "Starting-from estimate. Final price is confirmed by the WeWash team; payment is after service."
      };
      return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: data };
    } catch (e) {
      throw new ToolError(e instanceof Error ? e.message : "Could not calculate estimate");
    }
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.87.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-my-bookings.ts
var list_my_bookings_default = defineTool3({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List the signed-in customer's WeWash bookings, newest first.",
  inputSchema: { limit: z2.number().int().min(1).max(50).default(10) },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("bookings").select("id, status, scheduled_date, scheduled_time, total_amount, currency, customer_address, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const bookings = (data ?? []).map((b) => ({
      id: b.id,
      status: b.status,
      scheduledDate: b.scheduled_date,
      scheduledTime: b.scheduled_time,
      totalAmount: b.total_amount,
      currency: b.currency ?? "ZMW",
      address: b.customer_address,
      createdAt: b.created_at
    }));
    return { content: [{ type: "text", text: JSON.stringify(bookings) }], structuredContent: { bookings } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ouggluzwawtvyxwighsk";
var mcp_default = defineMcp({
  name: "wewash-global",
  title: "WeWash Global",
  version: "0.1.0",
  instructions: "Tools for WeWash, a premium cleaning, maid, pool and car detailing service in Lusaka, Zambia. Use list_services for options, estimate_price for 'starting from' estimates in ZMW (final price confirmed by the team, paid after service), and list_my_bookings for the signed-in customer's bookings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, estimate_price_default, list_my_bookings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
