// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdhgifwlafjfezlxlkom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkaGdpZndsYWZqZmV6bHhsa29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Njg5MDYsImV4cCI6MjA2ODI0NDkwNn0.91An5BZu05VUvdG1ipMqd6oaJ_qNlRnvVz3xOArDRC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});